package Tests;

import algorithms.Graph_Algo;
import dataStructure.DGraph;
import dataStructure.NodeData;
import dataStructure.graph;
import dataStructure.node_data;
import gameClient.*;
import org.junit.Test;
import utils.Point3D;
import algorithms.graph_algorithms;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import static org.junit.Assert.*;

public class Graph_AlgoTest {

    @Test
    public void init() {
        Graph_Algo g1 = new Graph_Algo();
        DGraph DG = new DGraph();
        NodeData n1 = new NodeData(1,2,3);
        NodeData n2 = new NodeData(1,2,3);
        NodeData n3 = new NodeData(1,2,3);
        NodeData n4 = new NodeData(1,2,3);
        NodeData n5 = new NodeData(1,2,3);
        NodeData n6 = new NodeData(1,2,3);
        DG.addNode(n1);
        DG.addNode(n2);
        DG.addNode(n3);
        DG.addNode(n4);
        DG.addNode(n5);
        DG.addNode(n6);
        DG.connect(1,2,5);
        DG.connect(1,3,5);
        DG.connect(1,4,5);
        DG.connect(6,2,5);
        DG.connect(6,5,5);
        DG.connect(6,4,5);
        g1.init(DG);
        assertEquals(DG,g1.getGraph());
    }

    @Test
    public void testInit() {
        Graph_Algo g = new Graph_Algo();
        DGraph DG = new DGraph();
        NodeData n1 = new NodeData(1,2,3);
        NodeData n2 = new NodeData(1,2,3);
        NodeData n3 = new NodeData(1,2,3);
        NodeData n4 = new NodeData(1,2,3);
        NodeData n5 = new NodeData(1,2,3);
        NodeData n6 = new NodeData(1,2,3);
        DG.addNode(n1);
        DG.addNode(n2);
        DG.addNode(n3);
        DG.addNode(n4);
        DG.addNode(n5);
        DG.addNode(n6);
        DG.connect(1,2,5);
        DG.connect(1,3,5);
        DG.connect(1,4,5);
        DG.connect(6,2,5);
        DG.connect(6,5,5);
        DG.connect(6,4,5);
        g.init(DG);
        g.save("TestSave");
        Graph_Algo g2 = new Graph_Algo();
        g2.init("TestSave");
        Boolean flag = g.getGraph().getEdge(1,2).getWeight() == g2.getGraph().getEdge(1,2).getWeight();
        Boolean flag2 = g.isConnected() == g2.isConnected();
        assertEquals(true,flag);
        assertEquals(true,flag2);

    }

    @Test
    public void save() {
        Graph_Algo g = new Graph_Algo();
        DGraph DG = new DGraph();
        NodeData n1 = new NodeData(100,200,3);
        NodeData n2 = new NodeData(150,200,3);
        NodeData n3 = new NodeData(300,450,3);
        NodeData n4 = new NodeData(450,500,3);
        NodeData n5 = new NodeData(320,600,3);
        NodeData n6 = new NodeData(226,260,3);
        DG.addNode(n1);
        DG.addNode(n2);
        DG.addNode(n3);
        DG.addNode(n4);
        DG.addNode(n5);
        DG.addNode(n6);
        DG.connect(1,2,5);
        DG.connect(1,3,5);
        DG.connect(1,4,5);
        DG.connect(6,2,5);
        DG.connect(6,5,5);
        DG.connect(6,4,5);
        g.init(DG);
        g.save("TestSave");
        Graph_Algo g2 = new Graph_Algo();
        g2.init("TestSave");
        Boolean flag = g.getGraph().getEdge(1,2).getWeight() == g2.getGraph().getEdge(1,2).getWeight();
        Boolean flag2 = g.isConnected() == g2.isConnected();
        assertEquals(true,flag);
        assertEquals(true,flag2);
    }

    @Test
    public void isConnected() {
        Graph_Algo g = new Graph_Algo();
        DGraph DG = new DGraph();
        NodeData n1 = new NodeData(100,200,3);
        NodeData n2 = new NodeData(150,200,3);
        NodeData n3 = new NodeData(300,450,3);
        NodeData n4 = new NodeData(450,500,3);
        NodeData n5 = new NodeData(320,600,3);
        NodeData n6 = new NodeData(226,260,3);
        DG.addNode(n1);
        DG.addNode(n2);
        DG.addNode(n3);
        DG.addNode(n4);
        DG.addNode(n5);
        DG.addNode(n6);
        DG.connect(1,2,5);
        DG.connect(2,3,5);
        DG.connect(3,4,5);
        DG.connect(4,5,5);
        DG.connect(5,6,5);
        DG.connect(6,1,5);
        g.init(DG);
        assertEquals(true,g.isConnected());
        Graph_Algo g2 = new Graph_Algo();
        DGraph DG2 = new DGraph();
        NodeData n21 = new NodeData(100,200,3);
        NodeData n22 = new NodeData(150,200,3);
        NodeData n23 = new NodeData(300,450,3);
        NodeData n24 = new NodeData(450,500,3);
        NodeData n25 = new NodeData(320,600,3);
        NodeData n26 = new NodeData(226,260,3);
        DG.addNode(n21);
        DG.addNode(n22);
        DG.addNode(n23);
        DG.addNode(n24);
        DG.addNode(n25);
        DG.addNode(n26);
        DG.connect(1,2,5);
        DG.connect(2,3,5);
        DG.connect(3,4,5);
        DG.connect(4,5,5);
        DG.connect(5,6,5);
        DG.connect(6,2,5);
        g.init(DG);
        assertEquals(false,g.isConnected());
        Graph_Algo g3 = new Graph_Algo();
        DGraph DG3 = new DGraph();
        NodeData n31 = new NodeData(100,200,3);
        NodeData n32 = new NodeData(150,200,3);
        DG3.addNode(n31);
        DG3.addNode(n32);
        DG3.connect(1,2,4);
        DG3.connect(2,1,4);
        g3.init(DG3);
        assertEquals(true,g3.isConnected());

    }
    //------------------- NEED TO LOOKOUT AT CONNECT!! DO NOT CHANGE ID THERE IS CONNECTION!
    @Test
    public void shortestPathDist() {
        Graph_Algo g = new Graph_Algo();
        DGraph DG = new DGraph();
        NodeData n1 = new NodeData(100,200,3);
        NodeData n2 = new NodeData(150,200,3);
        NodeData n3 = new NodeData(300,450,3);
        NodeData n4 = new NodeData(450,500,3);
        NodeData n5 = new NodeData(320,600,3);
        NodeData n6 = new NodeData(226,260,3);
        DG.addNode(n1);
        DG.addNode(n2);
        DG.addNode(n3);
        DG.addNode(n4);
        DG.addNode(n5);
        DG.addNode(n6);
        DG.connect(1,2,5);
        DG.connect(2,3,5);
        DG.connect(3,4,5);
        DG.connect(4,5,5);
        DG.connect(5,6,5);
        DG.connect(6,1,5);
        g.init(DG);
        boolean flag = 25 == g.shortestPathDist(1,6);
        assertEquals(true,flag);
        DG.connect(1,2,1);
        DG.connect(2,3,2);
        DG.connect(3,4,3);
        DG.connect(4,5,4);
        DG.connect(5,6,5);
        DG.connect(1,6,10);
        g.init(DG);
        flag = 10 == g.shortestPathDist(1,6);
        DG.reset();
        assertEquals(true,flag);
        NodeData b1 = new NodeData(100,200,3);
        NodeData b2 = new NodeData(150,200,3);
        NodeData b3 = new NodeData(300,450,3);
        NodeData b4 = new NodeData(450,500,3);
        NodeData b5 = new NodeData(320,600,3);
        NodeData b6 = new NodeData(226,260,3);
        DG.addNode(b1);
        DG.addNode(b2);
        DG.addNode(b3);
        DG.addNode(b4);
        DG.addNode(b5);
        DG.addNode(b6);
        DG.connect(1,2,1);
        DG.connect(2,3,2);
        DG.connect(3,4,3);
        DG.connect(4,5,4);
        DG.connect(5,6,5);
        DG.connect(1,6,16);
        g.init(DG);
        flag = 15 == g.shortestPathDist(1,6);
        assertEquals(true,flag);
    }

    @Test
    public void shortestPath() {
        Point3D x = new Point3D(14,4,0);
        Point3D x2 = new Point3D(-75,14,0);
        Point3D x3 = new Point3D(80,5,0);
        Point3D x4 = new Point3D(1,4,0);
        Point3D x5 = new Point3D(-5,1,0);
        Point3D x6 = new Point3D(8,3,0);
        Point3D x7 = new Point3D(4,1,0);
        Point3D x8 = new Point3D(75,14,0);
        node_data a1 = new NodeData(x);
        node_data a2 = new NodeData(x2);
        node_data a3 = new NodeData(x3);
        node_data a4 = new NodeData(x4);
        node_data a5 = new NodeData(x5);
        node_data a6 = new NodeData(x6);
        node_data a7 = new NodeData(x7);
        node_data a8 = new NodeData(x8);
        DGraph d = new DGraph();
        d.addNode(a1);
        d.addNode(a2);
        d.addNode(a3);
        d.addNode(a4);
        d.addNode(a5);
        d.addNode(a6);
        d.addNode(a7);
        d.addNode(a8);
        d.connect(a1.getKey(),a2.getKey(),5);
        d.connect(a1.getKey(),a5.getKey(),2);
        d.connect(a1.getKey(),a3.getKey(),6);
        d.connect(a3.getKey(),a4.getKey(),7);
        d.connect(a2.getKey(),a8.getKey(),8);
        d.connect(a2.getKey(),a7.getKey(),3);
        d.connect(a5.getKey(),a6.getKey(),2);
        d.connect(a6.getKey(),a7.getKey(),3);
        d.connect(a7.getKey(),a6.getKey(),3);
        Graph_Algo p = new Graph_Algo();
        p.init(d);
        List<node_data> ans = new LinkedList<node_data>();
        ans = p.shortestPath(1,7);
        List<node_data> test = new LinkedList<node_data>();
        test.add(a1);
        test.add(a5);
        test.add(a6);
        test.add(a7);
        assertEquals(test.get(0).getKey(),ans.get(0).getKey());
        assertEquals(test.get(1).getKey(),ans.get(1).getKey());
        assertEquals(test.get(2).getKey(),ans.get(2).getKey());
        assertEquals(test.get(3).getKey(),ans.get(3).getKey());
    }

    @Test
    public void TSP() {
        NodeData n1 = new NodeData(-200,-200,3);
        NodeData n2 = new NodeData(-400   ,300,3);
        NodeData n3 = new NodeData(300,150,3);
        NodeData n4 = new NodeData(380,-300,3);
        NodeData n5 = new NodeData(150,-400,3);
        NodeData n6 = new NodeData(0,-450,3);
        Point3D x = new Point3D(-400,300,0);
        Point3D x2 = new Point3D(300,150,0);
        Point3D x3 = new Point3D(380,-300,0);
        Point3D x4 = new Point3D(150,-400,0);
        Point3D x5 = new Point3D(0,-450,0);
        Point3D x6 = new Point3D(200,-300,0);
        Point3D x7 = new Point3D(-400,-150,0);
        Point3D x8 = new Point3D(-400,120,0);
        NodeData a1 = new NodeData(x);
        NodeData a2 = new NodeData(x2);
        NodeData a3 = new NodeData(x3);
        NodeData a4 = new NodeData(x4);
        NodeData a5 = new NodeData(x5);
        NodeData a6 = new NodeData(x6);
        NodeData a7 = new NodeData(x7);
        NodeData a8 = new NodeData(x8);
        DGraph d = new DGraph();
        d.addNode(a1);
        d.addNode(a2);
        d.addNode(a3);
        d.addNode(a4);
        d.addNode(a5);
        d.addNode(a6);
        d.addNode(a7);
        d.addNode(a8);
        d.connect(1,2,5);
        d.connect(1,5,2);
        d.connect(1,3,6);
        d.connect(1,6,5);
        d.connect(3,4,7);
        d.connect(2,8,8);
        d.connect(2,7,3);
        d.connect(5,1,5);
        d.connect(5,6,2);
        d.connect(6,1,3);
        d.connect(6,5,3);
        d.connect(6,7,3);
        d.connect(7,6,3);
        Graph_Algo p = new Graph_Algo();
        p.init(d);
        List<Integer> r = new LinkedList<>();
        r.add(1);
        r.add(6);
        r.add(5);
        List<node_data> ans = p.TSP(r);
        MyGameGUI q = new MyGameGUI();
        //q.init(p);
        q.MainDraw();
        assertEquals(ans.get(0).getKey(),1);
        assertEquals(ans.get(1).getKey(),5);
        assertEquals(ans.get(2).getKey(),6);
        List<Integer> test11 = new LinkedList<>();
        test11.add(1);
        test11.add(2);
        test11.add(6);
        test11.add(7);
        List<node_data> test1 = p.TSP(test11);
        assertEquals(test1.get(0).getKey(),1);
        assertEquals(test1.get(1).getKey(),5);
        assertEquals(test1.get(2).getKey(),6);
        assertEquals(test1.get(3).getKey(),7);
        assertEquals(test1.get(4).getKey(),6);
        assertEquals(test1.get(5).getKey(),1);
        assertEquals(test1.get(6).getKey(),2);

        Graph_Algo G = new Graph_Algo();
        Point3D p00 = new Point3D(1, 6, 0);
        Point3D p11 = new Point3D(0, 2, 3);
        Point3D p22 = new Point3D(2, 4, 0);
        Point3D p33 = new Point3D(5, 2, 0);
        Point3D p44 = new Point3D(6,5, 0);
        Point3D p55 = new Point3D(4,6, 0);
        Point3D p66 = new Point3D(3,5, 0);
        Point3D p77 = new Point3D(4,10,0);
        Point3D p88 = new Point3D(4.10,0);
        Point3D p99 = new Point3D(1,30);
        Point3D p10 = new Point3D(10,40);
        node_data node1 = new NodeData(p00);
        node_data node2 = new NodeData(p11);
        node_data node3 = new NodeData(p22);
        node_data node4 = new NodeData(p33);
        node_data node5 = new NodeData(p44);
        node_data node6 = new NodeData(p55);
        node_data node7 = new NodeData(p66);
        node_data node8 = new NodeData(p77);
        node_data node9 =new NodeData(p88);
        node_data node10 = new NodeData(p99);
        node_data node11 = new NodeData(p10);

        DGraph Dg = new DGraph();
        Dg.addNode(node1);
        Dg.addNode(node2);
        Dg.addNode(node3);
        Dg.addNode(node4);
        Dg.addNode(node5);
        Dg.addNode(node6);
        Dg.addNode(node7);
        Dg.addNode(node8);
        Dg.addNode(node9);
        Dg.addNode(node10);
        Dg.addNode(node11);


        Dg.connect(node1.getKey(), node2.getKey(), 5);
        Dg.connect(node1.getKey(), node3.getKey(), 3);
        Dg.connect(node1.getKey(), node4.getKey(), 2);
        Dg.connect(node2.getKey(), node5.getKey(), 2);
        Dg.connect(node3.getKey(), node6.getKey(), 4);
        Dg.connect(node3.getKey(),node1.getKey(),2);
        Dg.connect(node4.getKey(), node6.getKey(), 4);
        Dg.connect(node4.getKey(), node7.getKey(), 2);
        Dg.connect(node5.getKey(), node8.getKey(), 6);
        Dg.connect(node5.getKey(), node7.getKey(), 1);
        Dg.connect(node5.getKey(),node2.getKey(),4);
        Dg.connect(node6.getKey(),node11.getKey(),3);
        Dg.connect(node7.getKey(),node8.getKey(),4);
        Dg.connect(node7.getKey(),node6.getKey(),1);
        Dg.connect(node7.getKey(),node11.getKey(),9);
        Dg.connect(node8.getKey(),node7.getKey(),1);
        Dg.connect(node8.getKey(),node9.getKey(),9);
        Dg.connect(node9.getKey(),node8.getKey(),3);
        Dg.connect(node9.getKey(),node10.getKey(),5);
        Dg.connect(node10.getKey(),node9.getKey(),2);
        Dg.connect(node10.getKey(),node11.getKey(),1);
        Dg.connect(node11.getKey(),node10.getKey(),2);
        G.init(Dg);
        List<Integer> test22 = new LinkedList<>();
        test22.add(1);
        test22.add(3);
        test22.add(5);

        List<node_data> test2 = G.TSP(test22);
        assertEquals(test2.get(0).getKey(),1);
        assertEquals(test2.get(1).getKey(),3);
        assertEquals(test2.get(2).getKey(),1);
        assertEquals(test2.get(3).getKey(),2);
        assertEquals(test2.get(4).getKey(),5);


    }

    @Test
    public void copy() {Point3D x = new Point3D(14,4,0);
        Point3D x2 = new Point3D(-75,14,0);
        Point3D x3 = new Point3D(80,5,0);
        Point3D x4 = new Point3D(1,4,0);
        Point3D x5 = new Point3D(-5,1,0);
        Point3D x6 = new Point3D(8,3,0);
        Point3D x7 = new Point3D(4,1,0);
        Point3D x8 = new Point3D(75,14,0);
        node_data a1 = new NodeData(x);
        node_data a2 = new NodeData(x2);
        node_data a3 = new NodeData(x3);
        node_data a4 = new NodeData(x4);
        node_data a5 = new NodeData(x5);
        node_data a6 = new NodeData(x6);
        node_data a7 = new NodeData(x7);
        node_data a8 = new NodeData(x8);
        DGraph d = new DGraph();
        d.addNode(a1);
        d.addNode(a2);
        d.addNode(a3);
        d.addNode(a4);
        d.addNode(a5);
        d.addNode(a6);
        d.addNode(a7);
        d.addNode(a8);
        d.connect(a1.getKey(),a2.getKey(),5);
        d.connect(a1.getKey(),a5.getKey(),2);
        d.connect(a1.getKey(),a3.getKey(),6);
        d.connect(a3.getKey(),a4.getKey(),7);
        d.connect(a2.getKey(),a8.getKey(),8);
        d.connect(a2.getKey(),a7.getKey(),3);
        d.connect(a5.getKey(),a6.getKey(),2);
        d.connect(a6.getKey(),a7.getKey(),3);
        d.connect(a7.getKey(),a6.getKey(),3);
        Graph_Algo p = new Graph_Algo();
        p.init(d);
        graph g = new DGraph();
        g = p.copy();
        assertNotEquals(g,p.getGraph());
    }
}